 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lafassoftware;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Timothy Opiyo
 */
public class AfterLogin extends javax.swing.JFrame {

    String work = "", fname = "", lname = "", workStatus = "", email = "", tb, select = null;
    public static String work1, fname1, lname1, workStatus1, email1;

//int y=8;
    String[] columnNames = {"Employee ID", "First Name", "Second Name", "Area of practice", "Email"};
    DefaultTableModel model = new DefaultTableModel();
    
    public static String sessId,logger , timeIn, timeOut,username1;
    String[] sessionColumnNames = {"Session ID","Employee ID" ,"Username","Time signed in", "time signed out"};
    DefaultTableModel logModel = new DefaultTableModel();
    
    public static String clId,clFname , clLname, clPhone,clCase,clAssigned,clInvoice;
    String[] clientColumnNames = {"Client ID","First name" ,"Last name","Phone", "Case NO", "Assigned to","Invoice ID"};
    DefaultTableModel clientModel = new DefaultTableModel();

    /**
     * Creates new form AfterLogin
     */
    public AfterLogin() {
        initComponents();
        DisplayUser();
        DisplaySessions();
        DisplayClient();
        setLocationRelativeTo(null);
        setdate();
        
        lblEmp.setText(LawFirmHome.count);
        lblClient.setText(LawFirmHome.alClient);
        lblNoCase.setText(LawFirmHome.noOfCases);
    }

    public void setdate() {
        ActionListener dateaction = (ActionEvent e) -> {
            java.util.Date adminDate = new Date();
            labelAdminTime.setText(adminDate.getHours() + ":" + adminDate.getMinutes() + ":" + adminDate.getSeconds());
        };
        new javax.swing.Timer(1000, dateaction).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLarge = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        panelContainer = new javax.swing.JPanel();
        btnDashadmin = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnClientadmin = new javax.swing.JButton();
        btnTrends = new javax.swing.JButton();
        btnEvents = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        panelAdminMain = new javax.swing.JPanel();
        panelDash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblEmp = new javax.swing.JLabel();
        lblClients = new javax.swing.JLabel();
        lblCases = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        lblNoCase = new javax.swing.JLabel();
        panelEmp = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        btnEditAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSessionLogs = new javax.swing.JTable();
        panelClient = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableClientsAdmin = new javax.swing.JTable();
        txtSearchClient = new javax.swing.JTextField();
        btnSearchClient = new javax.swing.JButton();
        btnClientRefresh = new javax.swing.JButton();
        panelTrend = new javax.swing.JPanel();
        panelEvent = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEventsAdmin = new javax.swing.JTable();
        panelBill = new javax.swing.JPanel();
        labelAdminTime = new javax.swing.JLabel();
        signoutAdmin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAFUS - WELCOME");
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelLarge.setBackground(new java.awt.Color(0, 204, 204));

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Welcome admin");

        panelContainer.setBackground(new java.awt.Color(51, 51, 51));

        btnDashadmin.setText("Dashboard");
        btnDashadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashadminActionPerformed(evt);
            }
        });

        btnEmp.setText("Employees");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnClientadmin.setText("Clients");
        btnClientadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientadminActionPerformed(evt);
            }
        });

        btnTrends.setText("Trends");
        btnTrends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrendsActionPerformed(evt);
            }
        });

        btnEvents.setText("Events");
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });

        btnBilling.setText("Billings");
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });

        panelAdminMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Calender");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Billing");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Reports");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Database");

        jLabel5.setText("Number of employees :");

        jLabel6.setText("Number of clients :");

        jLabel7.setText("Number of cases :");

        jLabel9.setText("Bills awaiting payment:");

        jLabel10.setText("Bills already paid:");

        jLabel11.setText("total number of bills:");

        javax.swing.GroupLayout panelDashLayout = new javax.swing.GroupLayout(panelDash);
        panelDash.setLayout(panelDashLayout);
        panelDashLayout.setHorizontalGroup(
            panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashLayout.createSequentialGroup()
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7)
                            .addGroup(panelDashLayout.createSequentialGroup()
                                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDashLayout.createSequentialGroup()
                                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(69, 69, 69)
                                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCases, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblClients, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelDashLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNoCase, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 354, Short.MAX_VALUE))))
                    .addComponent(jSeparator8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator6))
                .addGap(175, 175, 175))
            .addGroup(panelDashLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDashLayout.setVerticalGroup(
            panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDashLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lblEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(lblClient, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNoCase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblClients, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(panelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCases, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(71, 71, 71))))
        );

        panelAdminMain.add(panelDash, "card2");

        panelEmp.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Work ID", "Name", "Status", "Email", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAdmin);
        if (tableAdmin.getColumnModel().getColumnCount() > 0) {
            tableAdmin.getColumnModel().getColumn(0).setHeaderValue("Work ID");
            tableAdmin.getColumnModel().getColumn(1).setHeaderValue("Name");
            tableAdmin.getColumnModel().getColumn(2).setHeaderValue("Status");
            tableAdmin.getColumnModel().getColumn(3).setHeaderValue("Email");
            tableAdmin.getColumnModel().getColumn(4).setHeaderValue("Title 5");
        }

        btnEditAdmin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnEditAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Edit admin_20px.png"))); // NOI18N
        btnEditAdmin.setText("Edit");
        btnEditAdmin.setBorder(null);
        btnEditAdmin.setContentAreaFilled(false);
        btnEditAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditAdminMouseExited(evt);
            }
        });
        btnEditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAdminActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDeleteAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Delete_20px.png"))); // NOI18N
        btnDeleteAdmin.setText("Delete");
        btnDeleteAdmin.setBorder(null);
        btnDeleteAdmin.setContentAreaFilled(false);
        btnDeleteAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteAdminMouseExited(evt);
            }
        });
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        txtSearch.setToolTipText("Enter work Id to search");

        btnsearch.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Search_20px.png"))); // NOI18N
        btnsearch.setToolTipText("Search");
        btnsearch.setBorder(null);
        btnsearch.setContentAreaFilled(false);
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchMouseExited(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Refresh_20px.png"))); // NOI18N
        btnDisplay.setToolTipText("Refresh");
        btnDisplay.setBorder(null);
        btnDisplay.setContentAreaFilled(false);
        btnDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDisplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDisplayMouseExited(evt);
            }
        });
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplay)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAdmin)
                    .addComponent(btnDeleteAdmin))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Employees table", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        tableSessionLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableSessionLogs);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Session Logs", jPanel2);

        javax.swing.GroupLayout panelEmpLayout = new javax.swing.GroupLayout(panelEmp);
        panelEmp.setLayout(panelEmpLayout);
        panelEmpLayout.setHorizontalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        panelEmpLayout.setVerticalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        panelAdminMain.add(panelEmp, "card2");

        tableClientsAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableClientsAdmin);

        txtSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchClientActionPerformed(evt);
            }
        });
        txtSearchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchClientKeyTyped(evt);
            }
        });

        btnSearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/searchClient.png"))); // NOI18N
        btnSearchClient.setContentAreaFilled(false);
        btnSearchClient.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Search_20px.png"))); // NOI18N
        btnSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClientActionPerformed(evt);
            }
        });

        btnClientRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/newFresh.png"))); // NOI18N
        btnClientRefresh.setContentAreaFilled(false);
        btnClientRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Refresh_20px.png"))); // NOI18N
        btnClientRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientLayout = new javax.swing.GroupLayout(panelClient);
        panelClient.setLayout(panelClientLayout);
        panelClientLayout.setHorizontalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        panelClientLayout.setVerticalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelAdminMain.add(panelClient, "card2");

        javax.swing.GroupLayout panelTrendLayout = new javax.swing.GroupLayout(panelTrend);
        panelTrend.setLayout(panelTrendLayout);
        panelTrendLayout.setHorizontalGroup(
            panelTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        panelTrendLayout.setVerticalGroup(
            panelTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        panelAdminMain.add(panelTrend, "card2");

        tableEventsAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableEventsAdmin);

        javax.swing.GroupLayout panelEventLayout = new javax.swing.GroupLayout(panelEvent);
        panelEvent.setLayout(panelEventLayout);
        panelEventLayout.setHorizontalGroup(
            panelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEventLayout.setVerticalGroup(
            panelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAdminMain.add(panelEvent, "card2");

        javax.swing.GroupLayout panelBillLayout = new javax.swing.GroupLayout(panelBill);
        panelBill.setLayout(panelBillLayout);
        panelBillLayout.setHorizontalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        panelBillLayout.setVerticalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        panelAdminMain.add(panelBill, "card2");

        labelAdminTime.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelAdminTime.setForeground(new java.awt.Color(255, 255, 255));
        labelAdminTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdminTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/clock.png"))); // NOI18N

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainerLayout.createSequentialGroup()
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnClientadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnTrends, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnDashadmin))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContainerLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnEmp))))
                    .addGroup(panelContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAdminTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAdminMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContainerLayout.setVerticalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDashadmin)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEmp)
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnClientadmin)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnTrends)
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEvents)
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnBilling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdminTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelAdminMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        signoutAdmin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        signoutAdmin.setForeground(new java.awt.Color(255, 255, 255));
        signoutAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Exit Sign_20px.png"))); // NOI18N
        signoutAdmin.setText("Sign-out");
        signoutAdmin.setBorder(null);
        signoutAdmin.setContentAreaFilled(false);
        signoutAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signoutAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signoutAdminMouseExited(evt);
            }
        });
        signoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutAdminActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LAFUS");

        javax.swing.GroupLayout panelLargeLayout = new javax.swing.GroupLayout(panelLarge);
        panelLarge.setLayout(panelLargeLayout);
        panelLargeLayout.setHorizontalGroup(
            panelLargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLargeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLargeLayout.setVerticalGroup(
            panelLargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLargeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutAdminActionPerformed
        AdminSessionEnd();
        LawFirmHome.main(null);
        dispose();
    }//GEN-LAST:event_signoutAdminActionPerformed

    private void btnDashadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashadminActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelDash);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnDashadminActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelEmp);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnClientadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientadminActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelClient);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnClientadminActionPerformed

    private void btnTrendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrendsActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelTrend);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnTrendsActionPerformed

    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelEvent);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnEventsActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        panelAdminMain.removeAll();
        panelAdminMain.repaint();
        panelAdminMain.revalidate();

        panelAdminMain.add(panelBill);
        panelAdminMain.repaint();
        panelAdminMain.revalidate();
    }//GEN-LAST:event_btnBillingActionPerformed
//function of display all button
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
        DisplayUser();
        select = null;
        work1 = null;
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void tableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdminMouseClicked
        int row = tableAdmin.getSelectedRow();
        tb = (String) tableAdmin.getModel().getValueAt(row, 4);
        work1 = (String) tableAdmin.getModel().getValueAt(row, 0);
        fname1 = (String) tableAdmin.getModel().getValueAt(row, 1);
        lname1 = (String) tableAdmin.getModel().getValueAt(row, 2);
        workStatus1 = (String) tableAdmin.getModel().getValueAt(row, 3);
        email1 = (String) tableAdmin.getModel().getValueAt(row, 4);


    }//GEN-LAST:event_tableAdminMouseClicked
//function of delete button
    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        select = work1;
        if (select == null) {
            JOptionPane.showMessageDialog(null, "Select employee first");
        } else {
            deleteMethod();
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            DisplayUser();
        }
    }//GEN-LAST:event_btnDeleteAdminActionPerformed
//function of search button
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
        search();
    }//GEN-LAST:event_btnsearchActionPerformed
//function of edit button
    private void btnEditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAdminActionPerformed
        select = work1;
        if (select == null) {
            JOptionPane.showMessageDialog(null, "Select employee whose details you want to edit");
        } else {
            EditDialog edit = new EditDialog(this, true);
            edit.setVisible(true);
        }
    }//GEN-LAST:event_btnEditAdminActionPerformed

    private void signoutAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutAdminMouseEntered
        this.signoutAdmin.setForeground(Color.black);
    }//GEN-LAST:event_signoutAdminMouseEntered

    private void signoutAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutAdminMouseExited
        this.signoutAdmin.setForeground(Color.white);
    }//GEN-LAST:event_signoutAdminMouseExited

    private void btnsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseEntered
        this.btnsearch.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnsearchMouseEntered

    private void btnsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseExited
        this.btnsearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnsearchMouseExited

    private void btnDisplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseEntered
        this.btnDisplay.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDisplayMouseEntered

    private void btnDisplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseExited
        this.btnDisplay.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDisplayMouseExited

    private void btnEditAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditAdminMouseEntered
        this.btnEditAdmin.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnEditAdminMouseEntered

    private void btnEditAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditAdminMouseExited
        this.btnEditAdmin.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEditAdminMouseExited

    private void btnDeleteAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAdminMouseEntered
        this.btnDeleteAdmin.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDeleteAdminMouseEntered

    private void btnDeleteAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAdminMouseExited
        this.btnDeleteAdmin.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDeleteAdminMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        AdminSessionEnd();
    }//GEN-LAST:event_formWindowClosed

    private void txtSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchClientActionPerformed

    private void btnSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClientActionPerformed
         while (clientModel.getRowCount() != 0) {
            clientModel.removeRow(0);
        }
        searchClient();
    }//GEN-LAST:event_btnSearchClientActionPerformed

    private void txtSearchClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchClientKeyTyped
        char c = evt.getKeyChar();
        if ((c == java.awt.event.KeyEvent.VK_SPACE) || (c == 9 || c >= 58 && c <= 126 || c >= 33 && c <= 42 || c >= 44 && c <= 47)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSearchClientKeyTyped

    private void btnClientRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRefreshActionPerformed
        while (clientModel.getRowCount() != 0) {
            clientModel.removeRow(0);
        }
        DisplayClient();
    }//GEN-LAST:event_btnClientRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AfterLogin().setVisible(true);
        });
    }

    public void DisplayUser() {

        model.setColumnIdentifiers(columnNames);

        tableAdmin.setModel(model);
        // tableAdmin.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        tableAdmin.setFillsViewportHeight(true);

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
            PreparedStatement st = con.prepareStatement("select  emp_id,fname,lname,practice,email from  employee ");
            ResultSet rs = st.executeQuery();

            int i = 0;
            while (rs.next()) {
                work = rs.getString("emp_id");
                fname = rs.getString("fname");
                lname = rs.getString("lname");
                workStatus = rs.getString("practice");
                email = rs.getString("email");

                model.addRow(new Object[]{work, fname, lname, workStatus, email});
                i++;

            }

            if (i < 1) {
                JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
         
        } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
            // System.out.println(rt);
            JOptionPane.showMessageDialog(null, rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    } //end of dispalyuser method
    
    public void DisplaySessions() {

        logModel.setColumnIdentifiers(sessionColumnNames);

        tableSessionLogs.setModel(logModel);
        //tableSessionLogs.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        tableSessionLogs.setFillsViewportHeight(true);

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
            PreparedStatement st = con.prepareStatement("select  session_id,logger_id,username,signin_time,signout_time from  session_logs");
            ResultSet rs = st.executeQuery();

            int i = 0;
            while (rs.next()) {
                sessId = rs.getString("session_id");
                logger = rs.getString("logger_id");
                username1 = rs.getString("username");
                timeIn = rs.getString("signin_time");
                timeOut = rs.getString("signout_time");

                logModel.addRow(new Object[]{sessId,logger ,username1,timeIn, timeOut});
                i++;

            }
         
        } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
            // System.out.println(rt);
            JOptionPane.showMessageDialog(null, rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void DisplayClient(){

        clientModel.setColumnIdentifiers(clientColumnNames);

        tableClientsAdmin.setModel(clientModel);
      
        tableClientsAdmin.setFillsViewportHeight(true);

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
            PreparedStatement st = con.prepareStatement("select  client_natid,client_fname,client_lname,cl_phone,case_no,assigned_to,invoice_id from newclient");
            ResultSet rs = st.executeQuery();

            int i = 0;
            while (rs.next()) {
                clId = rs.getString("client_natid");
                clFname = rs.getString("client_fname");
                clLname = rs.getString("client_lname");
                clPhone = rs.getString("cl_phone");
                clCase = rs.getString("case_no");
                clAssigned = rs.getString("assigned_to");
                clInvoice = rs.getString("invoice_id");
                clientModel.addRow(new Object[]{clId, clFname, clLname, clPhone, clCase,clAssigned,clInvoice});
                i++;

            }

            if (i < 1) {
                JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
         
        } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
            // System.out.println(rt);
            JOptionPane.showMessageDialog(null, rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    public void searchClient(){
        clientModel.setColumnIdentifiers(clientColumnNames);

        tableClientsAdmin.setModel(clientModel);

        tableClientsAdmin.setFillsViewportHeight(true);
        String x = txtSearchClient.getText().trim();
        if (x.equals("")) {
            JOptionPane.showMessageDialog(null, "Please type in client's ID then click search or press enter");
        } else {

            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
                PreparedStatement st = con.prepareStatement("select  client_natid,client_fname,client_lname,cl_phone,case_no,assigned_to,invoice_id from newclient where client_natid=" + x);
                //st.setString(1, tb);
                ResultSet rs = st.executeQuery();
                int i = 0;
            while (rs.next()) {
                clId = rs.getString("client_natid");
                clFname = rs.getString("client_fname");
                clLname = rs.getString("client_lname");
                clPhone = rs.getString("cl_phone");
                clCase = rs.getString("case_no");
                clAssigned = rs.getString("assigned_to");
                clInvoice = rs.getString("invoice_id");
                clientModel.addRow(new Object[]{clId, clFname, clLname, clPhone, clCase,clAssigned,clInvoice});
                i++;

                }

            } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
                // System.out.println(rt);
                JOptionPane.showMessageDialog(null,rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    public void deleteMethod() {
        //String x = txtPing.getText();
        int n = 0;

        if (tb.equals("")) {
            JOptionPane.showMessageDialog(null, "You have not selected any record");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
                PreparedStatement ps = con.prepareStatement("delete from employee where email=?");

                ps.setString(1, tb);

                int response = JOptionPane.showConfirmDialog(null, "Do you want to delete selected user?",
                        "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (response == JOptionPane.NO_OPTION) {

                } else if (response == JOptionPane.CLOSED_OPTION) {

                } else if (response == JOptionPane.YES_OPTION) {
                    n = ps.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(null, "DELETED SUCCESSFULLY");

                    } else {
                        JOptionPane.showMessageDialog(null, "failed");
                    }
                }

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            }

        }//end of else
    }//end of method delete method

    public void search() {
        model.setColumnIdentifiers(columnNames);

        tableAdmin.setModel(model);
        // tableAdmin.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        tableAdmin.setFillsViewportHeight(true);
        String x = txtSearch.getText();
        if (x.equals("")) {
            JOptionPane.showMessageDialog(null, "Nothing to search");
        } else {

            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
                PreparedStatement st = con.prepareStatement("select emp_id,fname,lname,practice,email from  employee where emp_id=" + x);
                //st.setString(1, tb);
                ResultSet rs = st.executeQuery();
                int i = 0;
                while (rs.next()) {
                    work = rs.getString("emp_id");
                    fname = rs.getString("fname");
                    lname = rs.getString("lname");
                    workStatus = rs.getString("practice");
                    email = rs.getString("email");

                    model.addRow(new Object[]{work, fname, lname, workStatus, email});
                    i++;

                }

                if (i < 1) {
                    JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
                }else if(x.equals("")){JOptionPane.showMessageDialog(null, "Enter Employees ID to search");}
             
            } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
                // System.out.println(rt);
                JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    } //end of method search
    
     public void AdminSessionEnd(){

        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
            Statement statement = con.createStatement();

            // SQL Insert
            String sql = "UPDATE session_logs SET signout_time = NOW() where username ='t'";

            statement.execute(sql);
            //status  = true;
        } catch (ClassNotFoundException | SQLException | HeadlessException es) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, "Log out of reach");
            JOptionPane.showMessageDialog(null, es.getMessage());
        }

//end of if statement that validate the form
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnClientRefresh;
    private javax.swing.JButton btnClientadmin;
    private javax.swing.JButton btnDashadmin;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnEditAdmin;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnSearchClient;
    private javax.swing.JButton btnTrends;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAdminTime;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblClients;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblNoCase;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panelAdminMain;
    private javax.swing.JPanel panelBill;
    private javax.swing.JPanel panelClient;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelDash;
    private javax.swing.JPanel panelEmp;
    private javax.swing.JPanel panelEvent;
    private javax.swing.JPanel panelLarge;
    private javax.swing.JPanel panelTrend;
    private javax.swing.JButton signoutAdmin;
    private javax.swing.JTable tableAdmin;
    private javax.swing.JTable tableClientsAdmin;
    private javax.swing.JTable tableEventsAdmin;
    private javax.swing.JTable tableSessionLogs;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchClient;
    // End of variables declaration//GEN-END:variables
}
