/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lafassoftware;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Timothy Opiyo
 */
public class ClientsViewDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClientsViewDialog
     *
     * @param parent
     * @param modal
     */
    public ClientsViewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        DisplayInfo();
        DisplayInfoInvoice();
        redIcon();

        jTextField_Fname.setText(FrameSignIn.fnameTable);
        jTextField_Lname.setText(FrameSignIn.lnameTable);
        jTextField_NatId.setText(FrameSignIn.clientId1);
        jComboBox_CaseStatus.setSelectedItem(FrameSignIn.caseStatus1);
        jTextField_AssignedTo.setText(FrameSignIn.assignedTo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupUpdatePaidUnpaid = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField_Fname = new javax.swing.JTextField();
        jTextField_Lname = new javax.swing.JTextField();
        jTextField_NatId = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_AssignedTo = new javax.swing.JTextField();
        clientsViewExit = new javax.swing.JButton();
        clientsViewUpdate = new javax.swing.JButton();
        jComboBox_CaseStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_CaseNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_UpdateTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_invoiceId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_paid = new javax.swing.JComboBox<>();
        redIcon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LAFUS-VIEW AND/OR UPDATE CLIENT DETAILS");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "View and/or update client details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        clientsViewExit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clientsViewExit.setForeground(new java.awt.Color(255, 255, 255));
        clientsViewExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/exitClient.png"))); // NOI18N
        clientsViewExit.setText("Exit");
        clientsViewExit.setContentAreaFilled(false);
        clientsViewExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/exitclientrollover.png"))); // NOI18N
        clientsViewExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientsViewExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientsViewExitMouseExited(evt);
            }
        });
        clientsViewExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsViewExitActionPerformed(evt);
            }
        });

        clientsViewUpdate.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        clientsViewUpdate.setForeground(new java.awt.Color(255, 255, 255));
        clientsViewUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/updateedit.png"))); // NOI18N
        clientsViewUpdate.setText("Update");
        clientsViewUpdate.setContentAreaFilled(false);
        clientsViewUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/updaterollover.png"))); // NOI18N
        clientsViewUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientsViewUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientsViewUpdateMouseExited(evt);
            }
        });
        clientsViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsViewUpdateActionPerformed(evt);
            }
        });

        jComboBox_CaseStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select case status", "Pending", "Disposed" }));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Client national ID");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Assigned to");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last name");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Case status");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Case Number");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Invoice details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField_UpdateTotal.setEditable(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clients billing total");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Invoice ID");

        txt_invoiceId.setEditable(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Paid or not yet paid");

        jComboBox_paid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not yet billed", "Paid", "Not yet" }));

        redIcon.setBackground(new java.awt.Color(255, 0, 0));
        redIcon.setToolTipText("Not yet billed");
        redIcon.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jTextField_UpdateTotal)
                        .addComponent(txt_invoiceId, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redIcon)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_UpdateTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_invoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_CaseStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_AssignedTo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jTextField_Lname)
                    .addComponent(jTextField_NatId)
                    .addComponent(jTextField_Email)
                    .addComponent(jTextField_Fname)
                    .addComponent(jTextField_CaseNo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(clientsViewUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientsViewExit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_NatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_AssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_CaseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientsViewExit)
                            .addComponent(clientsViewUpdate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientsViewExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsViewExitMouseEntered
        clientsViewExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_clientsViewExitMouseEntered

    private void clientsViewExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsViewExitMouseExited
        clientsViewExit.setForeground(Color.white);
    }//GEN-LAST:event_clientsViewExitMouseExited

    private void clientsViewUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsViewUpdateMouseEntered
        this.clientsViewUpdate.setForeground(Color.BLACK);
    }//GEN-LAST:event_clientsViewUpdateMouseEntered

    private void clientsViewUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsViewUpdateMouseExited
        this.clientsViewUpdate.setForeground(Color.white);
    }//GEN-LAST:event_clientsViewUpdateMouseExited

    private void clientsViewExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsViewExitActionPerformed
        dispose();
    }//GEN-LAST:event_clientsViewExitActionPerformed

    private void clientsViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsViewUpdateActionPerformed
        try {
            String url = "jdbc:mysql://localhost/lafus?useSSL = false";
            Connection conn;
            conn = DriverManager.getConnection(url, "root", "");
            //for newclient
            String total1 = jTextField_UpdateTotal.getText();
            String value1 = jTextField_Fname.getText();
            String value2 = jTextField_Lname.getText();
            String value3 = jTextField_NatId.getText();
            String value4 = jTextField_Email.getText();
            String value6 = (String) jComboBox_CaseStatus.getSelectedItem();
            //for client_invoice
            String value7 = (String) jComboBox_paid.getSelectedItem();

            String sql = "UPDATE newclient SET client_fname='" + value1 + "',client_lname='" + value2 + "',client_natid='" + value3 + "',client_mail='" + value4 + "',"
                    + "case_status='" + value6 + "' WHERE client_natid='" + jTextField_NatId.getText()+ "'";
            PreparedStatement pst;
            pst = null;
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            if(total1.equals("")){ JOptionPane.showMessageDialog(null, "Client matter is not yet billed");}
            else{
            String sql2 = "UPDATE client_invoice SET paid_notpaid='" + value7 + "' WHERE invoice_id='" + txt_invoiceId.getText()+ "'";
            PreparedStatement pst2;
            pst2 = null;
            pst2 = conn.prepareStatement(sql2);
            pst2.execute();
            JOptionPane.showMessageDialog(null, "Client details updated successfully");
            dispose();}
            
            


        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        

                                              
    }//GEN-LAST:event_clientsViewUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsViewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ClientsViewDialog dialog = new ClientsViewDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public static  void DisplayInfo() {
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus", "root", "");
            PreparedStatement st = con.prepareStatement("select client_mail,case_no,invoice_id from  newclient where client_natid='" +FrameSignIn.clientId1+"'");
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String clientMail1 = rs.getString("client_mail");
                jTextField_Email.setText(clientMail1);
                String clientCaseNo = rs.getString("case_no");
                jTextField_CaseNo.setText(clientCaseNo);
                String invoiceId = rs.getString("invoice_id");
                txt_invoiceId.setText(invoiceId);

            }

        } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
            // System.out.println(rt);
            JOptionPane.showMessageDialog(null, rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public static void DisplayInfoInvoice() {

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
            PreparedStatement st = con.prepareStatement("select total,paid_notpaid from client_invoice where invoice_id=" + txt_invoiceId.getText());
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String total = rs.getString("total");
                jTextField_UpdateTotal.setText(total);
                String paidNotPaid = rs.getString("paid_notpaid");
                jComboBox_paid.setSelectedItem(paidNotPaid);

            }

        } catch (ClassNotFoundException | SQLException | HeadlessException rt) {
            // System.out.println(rt);
            JOptionPane.showMessageDialog(null, rt.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    public void redIcon(){
        String Updatetotal=jTextField_UpdateTotal.getText();
    if(Updatetotal.equals("")){redIcon.enable();}
    else {redIcon.setVisible(false);}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupUpdatePaidUnpaid;
    private javax.swing.JButton clientsViewExit;
    private javax.swing.JButton clientsViewUpdate;
    private static javax.swing.JComboBox<String> jComboBox_CaseStatus;
    private static javax.swing.JComboBox<String> jComboBox_paid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JTextField jTextField_AssignedTo;
    private static javax.swing.JTextField jTextField_CaseNo;
    private static javax.swing.JTextField jTextField_Email;
    private static javax.swing.JTextField jTextField_Fname;
    private static javax.swing.JTextField jTextField_Lname;
    private static javax.swing.JTextField jTextField_NatId;
    private static javax.swing.JTextField jTextField_UpdateTotal;
    private javax.swing.JButton redIcon;
    private static javax.swing.JTextField txt_invoiceId;
    // End of variables declaration//GEN-END:variables
}
