/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lafassoftware;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Timothy Opiyo
 */
public class JframeFeature extends javax.swing.JFrame {

    /**
     * Creates new form JframeFeature
     *
     * @throws java.io.IOException
     */
    public JframeFeature() throws IOException {
        initComponents();
        setLocationRelativeTo(null);

        //add application icon
        String imagepath = "/my/lafassoftware/ScalesForToolbar.png";
        InputStream imgstream = JframeFeature.class.getResourceAsStream(imagepath);
        BufferedImage myImg = ImageIO.read(imgstream);
        this.setIconImage(myImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFeatures = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        buttonHome = new javax.swing.JButton();
        buttonDoc = new javax.swing.JButton();
        buttonMatter = new javax.swing.JButton();
        buttonSchedule = new javax.swing.JButton();
        buttonTrend = new javax.swing.JButton();
        buttonLabour = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        featureHome = new javax.swing.JPanel();
        ftHome = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFtHome = new javax.swing.JTextArea();
        docPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDoc = new javax.swing.JTextArea();
        schedulePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextSchedule = new javax.swing.JTextArea();
        matterPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextMatter = new javax.swing.JTextArea();
        trendsPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextTrends = new javax.swing.JTextArea();
        labourPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextLabour = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAW FIRM UTILITY SOFTWARE - FEATURES");
        setLocation(new java.awt.Point(300, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelFeatures.setBackground(new java.awt.Color(0, 102, 102));

        labelWelcome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("Welcome to LAFUS features page.");

        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Features_20px.png"))); // NOI18N
        buttonHome.setText("FEATURES ");
        buttonHome.setBorderPainted(false);
        buttonHome.setContentAreaFilled(false);
        buttonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHomeMouseExited(evt);
            }
        });
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Document_20px.png"))); // NOI18N
        buttonDoc.setText("DOCUMENTATION");
        buttonDoc.setContentAreaFilled(false);
        buttonDoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDocMouseExited(evt);
            }
        });
        buttonDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDocActionPerformed(evt);
            }
        });

        buttonMatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Key Exchange_20px.png"))); // NOI18N
        buttonMatter.setText("MATTER");
        buttonMatter.setContentAreaFilled(false);
        buttonMatter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonMatter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMatterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMatterMouseExited(evt);
            }
        });
        buttonMatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMatterActionPerformed(evt);
            }
        });

        buttonSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Calendar_20px.png"))); // NOI18N
        buttonSchedule.setText("SCHEDULES");
        buttonSchedule.setContentAreaFilled(false);
        buttonSchedule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonScheduleMouseExited(evt);
            }
        });
        buttonSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonScheduleActionPerformed(evt);
            }
        });

        buttonTrend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Trends_20px.png"))); // NOI18N
        buttonTrend.setText("TRENDS");
        buttonTrend.setContentAreaFilled(false);
        buttonTrend.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonTrend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonTrendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonTrendMouseExited(evt);
            }
        });
        buttonTrend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrendActionPerformed(evt);
            }
        });

        buttonLabour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Work_20px.png"))); // NOI18N
        buttonLabour.setText("LABOUR");
        buttonLabour.setContentAreaFilled(false);
        buttonLabour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLabour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLabourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLabourMouseExited(evt);
            }
        });
        buttonLabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLabourActionPerformed(evt);
            }
        });

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Backhome_20px.png"))); // NOI18N
        buttonBack.setText("BACK HOME");
        buttonBack.setContentAreaFilled(false);
        buttonBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBackMouseExited(evt);
            }
        });
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 153, 153));

        featureHome.setBackground(new java.awt.Color(102, 102, 102));
        featureHome.setLayout(new java.awt.CardLayout());

        ftHome.setBackground(new java.awt.Color(0, 204, 204));

        jTextFtHome.setEditable(false);
        jTextFtHome.setBackground(new java.awt.Color(102, 102, 102));
        jTextFtHome.setColumns(20);
        jTextFtHome.setForeground(new java.awt.Color(255, 255, 255));
        jTextFtHome.setRows(5);
        jTextFtHome.setText("\tTHE LAW FIRM UTILITY SOFTWARE (LAFUS).\n     \t                         FEATURES PREVIEW:\n\t....................................................................................................\n\t  LAFUS has a number of usable features that enables \n\t  a user be efficient in their legal process work, the\n\t  features include:\n\t   documentation\n\n\t   billing\n\n\t   matter follow ups\n\n\t   checking schedules\n\n\t   checking market trends\n\n\t   and information on labor force available in the firm.\n\t...................................................................................................\n");
        jScrollPane3.setViewportView(jTextFtHome);

        javax.swing.GroupLayout ftHomeLayout = new javax.swing.GroupLayout(ftHome);
        ftHome.setLayout(ftHomeLayout);
        ftHomeLayout.setHorizontalGroup(
            ftHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        ftHomeLayout.setVerticalGroup(
            ftHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(ftHome, "card2");

        docPanel.setBackground(new java.awt.Color(0, 204, 204));

        jTextDoc.setEditable(false);
        jTextDoc.setBackground(new java.awt.Color(102, 102, 102));
        jTextDoc.setColumns(20);
        jTextDoc.setForeground(new java.awt.Color(255, 255, 255));
        jTextDoc.setRows(5);
        jTextDoc.setText("\t\n\tDocumentation\n\t...........................................................................................\n\n\tUnder this feature the law firm will be able to \n\tperform the following functions:\n\n\t Create documents from the existing templates\n\n\t Follow up on court proceedings\n\n\t Follow up on contracts agreements\n");
        jScrollPane1.setViewportView(jTextDoc);

        javax.swing.GroupLayout docPanelLayout = new javax.swing.GroupLayout(docPanel);
        docPanel.setLayout(docPanelLayout);
        docPanelLayout.setHorizontalGroup(
            docPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        docPanelLayout.setVerticalGroup(
            docPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(docPanel, "card2");

        schedulePanel.setBackground(new java.awt.Color(0, 204, 204));

        jTextSchedule.setEditable(false);
        jTextSchedule.setBackground(new java.awt.Color(102, 102, 102));
        jTextSchedule.setColumns(20);
        jTextSchedule.setForeground(new java.awt.Color(255, 255, 255));
        jTextSchedule.setRows(5);
        jTextSchedule.setText("\n\tSchedules\n\t...............................................................................................\n\n\tThis feature is available for the law firm employees \n\tto do the following\n\n\t  Have reminders/to do lists\n\n\t  Create call logs\n\n\t  Follow up on board meetings\n\n\t  Follow up on clients and representative meetings\n");
        jScrollPane2.setViewportView(jTextSchedule);

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(schedulePanel, "card2");

        matterPanel.setBackground(new java.awt.Color(0, 204, 204));

        jTextMatter.setEditable(false);
        jTextMatter.setBackground(new java.awt.Color(102, 102, 102));
        jTextMatter.setColumns(20);
        jTextMatter.setForeground(new java.awt.Color(255, 255, 255));
        jTextMatter.setRows(5);
        jTextMatter.setText("\n\tClients/matter\n\t...............................................................................................................\n\tClients or matter as known in law is the core of the business\n\t enterprise that constitutes a law firm. \t\t\n\tBusiness done with the client should be swift and first to \n\tenable quick processing of documents and  \n\tother law related affairs, this feature therefore enables the \n\tlaw firm have:\n\n\t  Client record keeping safely\n\n\t  Ease up on client meetings\n\n\t  Case follow ups\n\n\t  Billing\n");
        jScrollPane4.setViewportView(jTextMatter);

        javax.swing.GroupLayout matterPanelLayout = new javax.swing.GroupLayout(matterPanel);
        matterPanel.setLayout(matterPanelLayout);
        matterPanelLayout.setHorizontalGroup(
            matterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        matterPanelLayout.setVerticalGroup(
            matterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(matterPanel, "card2");

        trendsPanel.setBackground(new java.awt.Color(0, 204, 204));

        jTextTrends.setEditable(false);
        jTextTrends.setBackground(new java.awt.Color(102, 102, 102));
        jTextTrends.setColumns(20);
        jTextTrends.setForeground(new java.awt.Color(255, 255, 255));
        jTextTrends.setRows(5);
        jTextTrends.setText("\t\n\n\tMarket/trends\n\t..................................................................................\n\tThis is a simple feature that enables the law \n\tfirm know its position within the market \n\tand may therefore help the firm strategize \n\tfor future success, it will include a business \n\tintelligence solution for the firm.\n");
        jScrollPane5.setViewportView(jTextTrends);

        javax.swing.GroupLayout trendsPanelLayout = new javax.swing.GroupLayout(trendsPanel);
        trendsPanel.setLayout(trendsPanelLayout);
        trendsPanelLayout.setHorizontalGroup(
            trendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        trendsPanelLayout.setVerticalGroup(
            trendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(trendsPanel, "card2");

        labourPanel.setBackground(new java.awt.Color(0, 204, 204));

        jTextLabour.setEditable(false);
        jTextLabour.setBackground(new java.awt.Color(102, 102, 102));
        jTextLabour.setColumns(20);
        jTextLabour.setForeground(new java.awt.Color(255, 255, 255));
        jTextLabour.setRows(5);
        jTextLabour.setText("\n\tLabor\n\t....................................................................\n\n\tThis feature helps the firm\n\n\t  monitor its work force\n\n\t  Do performance analysis\n\n\t  And plan for leaves or vacations\n");
        jScrollPane6.setViewportView(jTextLabour);

        javax.swing.GroupLayout labourPanelLayout = new javax.swing.GroupLayout(labourPanel);
        labourPanel.setLayout(labourPanelLayout);
        labourPanelLayout.setHorizontalGroup(
            labourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        labourPanelLayout.setVerticalGroup(
            labourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        featureHome.add(labourPanel, "card2");

        javax.swing.GroupLayout jPanelFeaturesLayout = new javax.swing.GroupLayout(jPanelFeatures);
        jPanelFeatures.setLayout(jPanelFeaturesLayout);
        jPanelFeaturesLayout.setHorizontalGroup(
            jPanelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFeaturesLayout.createSequentialGroup()
                        .addGroup(jPanelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonLabour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTrend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonMatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(buttonDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(featureHome, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelFeaturesLayout.setVerticalGroup(
            jPanelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFeaturesLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDoc)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMatter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonTrend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonLabour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBack)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(featureHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        LawFirmHome jframeHome = null;
        try {
            jframeHome = new LawFirmHome();
        } catch (IOException ex) {
            Logger.getLogger(JframeFeature.class.getName()).log(Level.SEVERE, null, ex);
        }
        jframeHome.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDocActionPerformed
        // TODO add your handling code here:
        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(docPanel);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonDocActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(ftHome);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonHomeActionPerformed

    //mouse entered and mouse exited mouse events

    private void buttonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseEntered
        // TODO add your handling code here:
        this.buttonHome.setBackground(Color.DARK_GRAY);
        this.buttonHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonHomeMouseEntered

    private void buttonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseExited
        // TODO add your handling code here:
        this.buttonHome.setBackground(Color.WHITE);
        this.buttonHome.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonHomeMouseExited

    private void buttonDocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDocMouseEntered
        // TODO add your handling code here:
        this.buttonDoc.setBackground(Color.DARK_GRAY);
        this.buttonDoc.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonDocMouseEntered

    private void buttonDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDocMouseExited
        // TODO add your handling code here:
        this.buttonDoc.setBackground(Color.WHITE);
        this.buttonDoc.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonDocMouseExited

    private void buttonScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonScheduleMouseEntered
        // TODO add your handling code here:
        this.buttonSchedule.setBackground(Color.DARK_GRAY);
        this.buttonSchedule.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonScheduleMouseEntered

    private void buttonScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonScheduleMouseExited
        // TODO add your handling code here:
        this.buttonSchedule.setBackground(Color.WHITE);
        this.buttonSchedule.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonScheduleMouseExited

    private void buttonMatterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMatterMouseEntered
        // TODO add your handling code here:
        this.buttonMatter.setBackground(Color.DARK_GRAY);
        this.buttonMatter.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonMatterMouseEntered

    private void buttonMatterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMatterMouseExited
        // TODO add your handling code here:
        this.buttonMatter.setBackground(Color.WHITE);
        this.buttonMatter.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonMatterMouseExited

    private void buttonTrendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTrendMouseEntered
        // TODO add your handling code here:
        this.buttonTrend.setBackground(Color.DARK_GRAY);
        this.buttonTrend.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonTrendMouseEntered

    private void buttonTrendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTrendMouseExited
        // TODO add your handling code here:
        this.buttonTrend.setBackground(Color.WHITE);
        this.buttonTrend.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonTrendMouseExited

    private void buttonLabourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLabourMouseEntered
        // TODO add your handling code here:
        this.buttonLabour.setBackground(Color.DARK_GRAY);
        this.buttonLabour.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonLabourMouseEntered

    private void buttonLabourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLabourMouseExited
        // TODO add your handling code here:
        this.buttonLabour.setBackground(Color.WHITE);
        this.buttonLabour.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonLabourMouseExited

    private void buttonBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackMouseEntered
        // TODO add your handling code here:
        this.buttonBack.setBackground(Color.DARK_GRAY);
        this.buttonBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_buttonBackMouseEntered

    private void buttonBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackMouseExited

        this.buttonBack.setBackground(Color.WHITE);
        this.buttonBack.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonBackMouseExited

    private void buttonScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonScheduleActionPerformed

        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(schedulePanel);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonScheduleActionPerformed

    private void buttonMatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMatterActionPerformed

        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(matterPanel);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonMatterActionPerformed

    private void buttonTrendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrendActionPerformed
        // TODO add your handling code here:
        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(trendsPanel);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonTrendActionPerformed

    private void buttonLabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLabourActionPerformed
        featureHome.removeAll();
        featureHome.repaint();
        featureHome.revalidate();

        featureHome.add(labourPanel);
        featureHome.repaint();
        featureHome.revalidate();
    }//GEN-LAST:event_buttonLabourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeFeature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeFeature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeFeature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeFeature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JframeFeature().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(JframeFeature.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDoc;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLabour;
    private javax.swing.JButton buttonMatter;
    private javax.swing.JButton buttonSchedule;
    private javax.swing.JButton buttonTrend;
    private javax.swing.JPanel docPanel;
    private javax.swing.JPanel featureHome;
    private javax.swing.JPanel ftHome;
    private javax.swing.JPanel jPanelFeatures;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextDoc;
    private javax.swing.JTextArea jTextFtHome;
    private javax.swing.JTextArea jTextLabour;
    private javax.swing.JTextArea jTextMatter;
    private javax.swing.JTextArea jTextSchedule;
    private javax.swing.JTextArea jTextTrends;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel labourPanel;
    private javax.swing.JPanel matterPanel;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JPanel trendsPanel;
    // End of variables declaration//GEN-END:variables
}
