/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.lafassoftware;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Timothy Opiyo
 */
public class LawFirmHome extends javax.swing.JFrame {
;
    public static String usernameLabel;
    public static String userId;
    public static String count = null;
    public static String alClient = null;
    public static String pendingCase = null;
    public static String assignedNo = null;
    public static String disposedCase = null;
    public static String sessID1 = null;
    public static String noOfCases = null;
    public static String schName = null;
    public static String schPriority = null;
    public static String schDate = null;
    /**
     * Creates new form LawFirmHome
     *
     * @throws java.io.IOException
     */
    public LawFirmHome() throws IOException {
        initComponents();
        setLocationRelativeTo(null);

        //setting the application's icon
        String imagepath = "/my/lafassoftware/ScalesForToolbar.png";
        InputStream imgstream = LawFirmHome.class.getResourceAsStream(imagepath);
        BufferedImage myImg = ImageIO.read(imgstream);
        this.setIconImage(myImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        featureButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        iconImage = new javax.swing.JLabel();
        jPanelAboutSign = new javax.swing.JPanel();
        panelSignIn = new javax.swing.JPanel();
        labelPassword = new javax.swing.JLabel();
        labelSignIn = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelQuestion = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaAbout = new javax.swing.JTextArea();
        backToSign = new javax.swing.JButton();
        panelSign = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        adminUser = new javax.swing.JTextField();
        btnProceed = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        adminPass = new javax.swing.JPasswordField();
        buttonBackS = new javax.swing.JButton();
        labelLafus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAW FIRM UTILITY SOFTWARE");
        setBackground(new java.awt.Color(0, 153, 204));
        setLocation(new java.awt.Point(300, 200));
        setMinimumSize(new java.awt.Dimension(808, 387));
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(0, 102, 102));

        labelHeader.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelHeader.setText("LAW FIRM UTILITY SOFTWARE");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        featureButton.setBackground(new java.awt.Color(0, 102, 102));
        featureButton.setForeground(new java.awt.Color(255, 255, 255));
        featureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Briefcasempyahome.png"))); // NOI18N
        featureButton.setText("FEATURES");
        featureButton.setBorder(null);
        featureButton.setContentAreaFilled(false);
        featureButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/briefcaserollover.png"))); // NOI18N
        featureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                featureButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                featureButtonMouseExited(evt);
            }
        });
        featureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featureButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(0, 102, 102));
        helpButton.setForeground(new java.awt.Color(255, 255, 255));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/heelporiginal.png"))); // NOI18N
        helpButton.setText("HELP");
        helpButton.setBorder(null);
        helpButton.setContentAreaFilled(false);
        helpButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Help_48px.png"))); // NOI18N
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButtonMouseExited(evt);
            }
        });
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        aboutButton.setBackground(new java.awt.Color(0, 102, 102));
        aboutButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/aboutoriginal.png"))); // NOI18N
        aboutButton.setText("ABOUT");
        aboutButton.setBorder(null);
        aboutButton.setContentAreaFilled(false);
        aboutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/About_48px.png"))); // NOI18N
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutButtonMouseExited(evt);
            }
        });
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        iconImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Scales_96px.png"))); // NOI18N
        iconImage.setText("jLabel1");

        jPanelAboutSign.setLayout(new java.awt.CardLayout());

        panelSignIn.setBackground(new java.awt.Color(0, 255, 255));

        labelPassword.setBackground(new java.awt.Color(51, 255, 255));
        labelPassword.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelPassword.setText("Password");
        labelPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labelPasswordKeyTyped(evt);
            }
        });

        labelSignIn.setBackground(new java.awt.Color(51, 255, 255));
        labelSignIn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelSignIn.setText("Get more access:");

        labelUsername.setBackground(new java.awt.Color(51, 255, 255));
        labelUsername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelUsername.setText("Username");

        username.setBackground(new java.awt.Color(0, 255, 204));
        username.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        username.setToolTipText("enter username");
        username.setBorder(null);
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(0, 255, 204));
        passwordField.setToolTipText("enter password");
        passwordField.setBorder(null);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 255, 204));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        labelQuestion.setBackground(new java.awt.Color(0, 0, 0));
        labelQuestion.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labelQuestion.setText("Dont have an account yet?");

        signInButton.setBackground(java.awt.Color.cyan);
        signInButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        signInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Enter_20px.png"))); // NOI18N
        signInButton.setText("Log in");
        signInButton.setToolTipText("Click to enter your page");
        signInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signInButton.setBorderPainted(false);
        signInButton.setContentAreaFilled(false);
        signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInButtonMouseExited(evt);
            }
        });
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        signUpButton.setBackground(java.awt.Color.cyan);
        signUpButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        signUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Add User Male_20px.png"))); // NOI18N
        signUpButton.setText("Sign up");
        signUpButton.setToolTipText("Click to create account");
        signUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signUpButton.setBorderPainted(false);
        signUpButton.setContentAreaFilled(false);
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpButtonMouseExited(evt);
            }
        });
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Edit User Male_25px.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/lafassoftware/Password_25px.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout panelSignInLayout = new javax.swing.GroupLayout(panelSignIn);
        panelSignIn.setLayout(panelSignInLayout);
        panelSignInLayout.setHorizontalGroup(
            panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignInLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuestion)
                    .addGroup(panelSignInLayout.createSequentialGroup()
                        .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(labelSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(passwordField)
                            .addComponent(jSeparator3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelSignInLayout.setVerticalGroup(
            panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignInLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignInLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignInLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelAboutSign.add(panelSignIn, "card2");

        panelAbout.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("ABOUT LAFUS (LAW FIRM UTILITY SOFTWARE).");

        jTxtAreaAbout.setEditable(false);
        jTxtAreaAbout.setBackground(new java.awt.Color(0, 255, 255));
        jTxtAreaAbout.setColumns(20);
        jTxtAreaAbout.setRows(5);
        jTxtAreaAbout.setText("LAFUS is a software that is made to enhance digitization \nof law firm activities and services and enable \nthem integrate it with the judicial system in a given country.\n........................................................................................................\nAbout product:\nPRODUCT VERSION: V1.016\nDEVELOPER: Timothy Opiyo\nYEAR INITIATED:2016\nPRODUCT SPONSORS: MASINDE MULIRO UNIVERSITY \nOF SCIENCE AND TECHNOLOGY\n(SCHOOL OF COMPUTING AND INFORMATICS)\nCOUNTRY OF ORIGIN: Kenya\n");
        jScrollPane1.setViewportView(jTxtAreaAbout);

        backToSign.setBackground(new java.awt.Color(0, 255, 255));
        backToSign.setText("BACK TO SIGN IN");
        backToSign.setBorder(null);
        backToSign.setBorderPainted(false);
        backToSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backToSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backToSignMouseExited(evt);
            }
        });
        backToSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backToSign, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backToSign, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelAboutSign.add(panelAbout, "card2");

        panelSign.setBackground(new java.awt.Color(0, 255, 255));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("SIGN UP NEW EMPLOYEE");

        adminUser.setBackground(new java.awt.Color(0, 255, 255));
        adminUser.setBorder(null);
        adminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserActionPerformed(evt);
            }
        });

        btnProceed.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnProceed.setText("PROCEED");
        btnProceed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProceed.setContentAreaFilled(false);
        btnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProceedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProceedMouseExited(evt);
            }
        });
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter administrator's details below and proceed");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        adminPass.setBackground(new java.awt.Color(0, 255, 255));
        adminPass.setBorder(null);

        buttonBackS.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonBackS.setText("BACK");
        buttonBackS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonBackS.setContentAreaFilled(false);
        buttonBackS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBackSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBackSMouseExited(evt);
            }
        });
        buttonBackS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSignLayout = new javax.swing.GroupLayout(panelSign);
        panelSign.setLayout(panelSignLayout);
        panelSignLayout.setHorizontalGroup(
            panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(107, 107, 107))
            .addGroup(panelSignLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(adminUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSignLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(185, 185, 185))
                            .addComponent(adminPass, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(buttonBackS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelSignLayout.setVerticalGroup(
            panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonBackS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanelAboutSign.add(panelSign, "card2");

        labelLafus.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        labelLafus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLafus.setText("LAFUS");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelHeader))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(iconImage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelLafus, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(featureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelAboutSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(labelHeader)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(iconImage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelLafus)
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(featureButton)
                            .addComponent(aboutButton)
                            .addComponent(helpButton)))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanelAboutSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void featureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featureButtonActionPerformed
        JframeFeature jframeFeature = null;
        try {
            jframeFeature = new JframeFeature();
        } catch (IOException ex) {
            Logger.getLogger(LawFirmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        jframeFeature.setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_featureButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        //SignUpFrame jframeSignUp = new SignUpFrame();
        jPanelAboutSign.removeAll();
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();

        jPanelAboutSign.add(panelSign);
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        jPanelAboutSign.removeAll();
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();

        jPanelAboutSign.add(panelAbout);
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed

        HelpDialog help = new HelpDialog(this, true);
        help.setVisible(true);

    }//GEN-LAST:event_helpButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        signinmethod();
        countPending();
        SessionLogs();
        countDisposed();
        pickSessID();
        countassigned();
        countCase();
        scheduleInfo();
    }//GEN-LAST:event_signInButtonActionPerformed

    private void featureButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_featureButtonMouseEntered
        this.featureButton.setBackground(Color.CYAN);
        this.featureButton.setForeground(Color.GREEN);// TODO add your handling code here:
    }//GEN-LAST:event_featureButtonMouseEntered

    private void featureButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_featureButtonMouseExited
        this.featureButton.setBackground(Color.CYAN);
        this.featureButton.setForeground(Color.WHITE); // TODO add your handling code here:
    }//GEN-LAST:event_featureButtonMouseExited

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        this.aboutButton.setBackground(Color.CYAN);
        this.aboutButton.setForeground(Color.GREEN);// TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void aboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseExited
        this.aboutButton.setBackground(Color.CYAN);
        this.aboutButton.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonMouseExited

    private void helpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseEntered
        this.helpButton.setBackground(Color.CYAN);
        this.helpButton.setForeground(Color.GREEN);// TODO add your handling code here:
    }//GEN-LAST:event_helpButtonMouseEntered

    private void helpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseExited
        this.helpButton.setBackground(Color.CYAN);
        this.helpButton.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_helpButtonMouseExited

    private void backToSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToSignActionPerformed
        jPanelAboutSign.removeAll();
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();

        jPanelAboutSign.add(panelSignIn);
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_backToSignActionPerformed

    private void backToSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToSignMouseEntered
        this.backToSign.setBackground(Color.DARK_GRAY);
        this.backToSign.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_backToSignMouseEntered

    private void backToSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToSignMouseExited
        this.backToSign.setBackground(Color.CYAN);
        this.backToSign.setForeground(Color.BLACK);       // TODO add your handling code here:
    }//GEN-LAST:event_backToSignMouseExited

    private void labelPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPasswordKeyPressed

    private void labelPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPasswordKeyTyped

    private void signInButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseEntered
        this.signInButton.setBackground(Color.GRAY);
        this.signInButton.setForeground(Color.BLUE);
    }//GEN-LAST:event_signInButtonMouseEntered

    private void signInButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseExited
        this.signInButton.setBackground(Color.CYAN);
        this.signInButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_signInButtonMouseExited

    private void signUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseEntered
        this.signUpButton.setBackground(Color.GRAY);
        this.signUpButton.setForeground(Color.BLUE);
    }//GEN-LAST:event_signUpButtonMouseEntered

    private void signUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseExited
        this.signUpButton.setBackground(Color.CYAN);
        this.signUpButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_signUpButtonMouseExited

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            signinmethod();
            countPending();
            countassigned();
            countDisposed();
            pickSessID();
            SessionLogs();
            countCase();
            scheduleInfo();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            passwordField.requestFocusInWindow();
        }
    }//GEN-LAST:event_usernameKeyPressed

    private void adminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUserActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        String userAdmin = adminUser.getText();
        String passAdmin = adminPass.getText();
        if(userAdmin.equals("timothy") && passAdmin.equals("stranger1")){NewSignUp.main(null);
        dispose();}
        else{JOptionPane.showMessageDialog(null, "Please confirm the username and password or contact the administrator");
        adminUser.setText("");
        adminPass.setText("");
        
        jPanelAboutSign.removeAll();
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();

        jPanelAboutSign.add(panelSignIn);
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();}
    }//GEN-LAST:event_btnProceedActionPerformed

    private void buttonBackSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackSActionPerformed
        jPanelAboutSign.removeAll();
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();

        jPanelAboutSign.add(panelSignIn);
        jPanelAboutSign.repaint();
        jPanelAboutSign.revalidate();
    }//GEN-LAST:event_buttonBackSActionPerformed

    private void btnProceedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseEntered
        btnProceed.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnProceedMouseEntered

    private void btnProceedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseExited
       btnProceed.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnProceedMouseExited

    private void buttonBackSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackSMouseEntered
       buttonBackS.setForeground(Color.BLUE);
    }//GEN-LAST:event_buttonBackSMouseEntered

    private void buttonBackSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackSMouseExited
        buttonBackS.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonBackSMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LawFirmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LawFirmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LawFirmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LawFirmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LawFirmHome().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(LawFirmHome.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    public void signinmethod() {
        
        
        String x = username.getText();
        String y = new String(passwordField.getPassword());
        if(x.equals(""))
        {JOptionPane.showMessageDialog(null, "Please enter username");username.requestFocusInWindow();}
        else if(y.equals(""))
        {JOptionPane.showMessageDialog(null, "Please enter password");passwordField.requestFocusInWindow();}
        else{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
            PreparedStatement st = con.prepareStatement("select emp_id,fname,lname,username,password from  employee where  username=? and password=?");
            st.setString(1, x);
            st.setString(2, y);
            ResultSet rs = st.executeQuery();

            PreparedStatement co = con.prepareStatement("select  count(emp_id) as id from  employee ");
            ResultSet rsCount = co.executeQuery();
            
            PreparedStatement com = con.prepareStatement("select  count(client_natid) as cid from  newclient ");
            ResultSet rsCom = com.executeQuery();
            
            int i = 0;
            if (rs.next()) {
                String a = rs.getString("fname");
                String b = rs.getString("lname");
                String c = rs.getString("emp_id");
                userId = c;
                usernameLabel = a + " " + b;
                
                

                FrameSignIn.main(null);
                dispose();
             if (rsCom.next())
                {alClient = rsCom.getString("cid");}
         
            } else if (x.equals("timothy") && y.equals("stranger1")) {
                if (rsCount.next()) 
                { count = rsCount.getString("id");}
                   
                if (rsCom.next())
                {alClient = rsCom.getString("cid");}
                
                AfterLogin.main(null);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Please signup or check your login details again");

            }
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
        }}
    }
    
    public void SessionLogs() {

        String strUser = username.getText();
        String strPass = passwordField.getText();
        String strLogger = userId;

        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
            Statement statement = con.createStatement();

            // SQL Insert
            String sql = "INSERT INTO session_logs " + "(logger_id,username,password)"
                    + "VALUES ('" + strLogger + "', '"
                     + strUser + "', '"
                    + strPass + "')";

            statement.execute(sql);
            String id="select session_id from session_logs where ";
            //status  = true;
        } catch (ClassNotFoundException | SQLException | HeadlessException es) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, "Log out of reach");
            JOptionPane.showMessageDialog(null, es.getMessage());
        }

//end of if statement that validate the form
    }

    public void pickSessID(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select session_id from session_logs where username='" +username.getText()+"'");
        ResultSet rsCos = cos.executeQuery();
        
        int i = 0;
            if (rsCos.next()) {
                
                sessID1 = rsCos.getString("session_id");}
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
    
    public void countPending(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select count(case_status) as those_pending from table_case  where case_status = 'pending' and emp_id =" + userId);
        ResultSet rsCos = cos.executeQuery();
        
        int i = 0;
            if (rsCos.next()) {
                
                pendingCase = rsCos.getString("those_pending");}
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
    
    public void countDisposed(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select count(case_status) as disposed from table_case  where case_status = 'disposed' and emp_id ='" + userId+"'");
        ResultSet rsCos = cos.executeQuery();
        
        int i = 0;
            if (rsCos.next()) {
                
                disposedCase = rsCos.getString("disposed");}
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
    
     public void countassigned(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select count(client_natid) as assigned from newclient where assigned_to =" + userId);
        ResultSet rsCos = cos.executeQuery();
        
        int i = 0;
            if (rsCos.next()) {
                
                assignedNo = rsCos.getString("assigned");}
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
    
     public void countCase(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select count(case_no) as no_cases from table_case");
        ResultSet rsCos = cos.executeQuery();
        
            if (rsCos.next()) {
                noOfCases = rsCos.getString("no_cases");}
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
     
     public void scheduleInfo(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lafus?useSSL = false", "root", "");
        PreparedStatement cos = con.prepareStatement("select schedule_name,priority,date_to_do from table_schedule where schedule_id = (select max(schedule_id) from table_schedule where sch_creator ='" + userId+"')");
        ResultSet rsCos = cos.executeQuery();
        
        int i = 0;
            if (rsCos.next()) {
                schName = rsCos.getString("schedule_name");
                schPriority = rsCos.getString("priority");
                schDate = rsCos.getString("date_to_do");
            }
            else{}
                
    }catch(ClassNotFoundException | SQLException | HeadlessException es){
    JOptionPane.showMessageDialog(null, es.getMessage());}
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JPasswordField adminPass;
    private javax.swing.JTextField adminUser;
    private javax.swing.JButton backToSign;
    private javax.swing.JButton btnProceed;
    private javax.swing.JButton buttonBackS;
    private javax.swing.JButton featureButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel iconImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelAboutSign;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTxtAreaAbout;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelLafus;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelSignIn;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelSign;
    private javax.swing.JPanel panelSignIn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
